export enum WebhookType {
  SUBSCRIPTION_PURCHASE_SUCCESSFUL = 'SUBSCRIPTION_PURCHASE_SUCCESSFUL',
  SUBSCRIPTION_RENEWAL_SUCCESSFUL = 'SUBSCRIPTION_RENEWAL_SUCCESSFUL',
  SUBSCRIPTION_RENEWAL_FAILED = 'SUBSCRIPTION_RENEWAL_FAILED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED',
}
